# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='post_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
