# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feedback_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
